services:
  - type: web
    name: matematikoy-django
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput  # Coleta arquivos estáticos antes do deploy
    startCommand: "gunicorn website.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        sync: false
